require('dotenv').config();
const OpenAI = require('openai');
const { logger } = require('../utils/logger');

/**
 * SimuAI Artificial Intelligence Service
 * Powered by Groq Cloud (Llama 3)
 */

let openai = null;
const useMockAI = process.env.USE_MOCK_AI === 'true';
const GROQ_MODEL = "llama3-8b-8192";

// Initialize AI Client
if (!useMockAI && process.env.GROQ_API_KEY) {
  try {
    openai = new OpenAI({
      apiKey: process.env.GROQ_API_KEY,
      baseURL: "https://api.groq.com/openai/v1" // Critical for Groq integration
    });
    logger.info('✓ AI Service initialized via Groq Cloud');
  } catch (error) {
    logger.error('Failed to initialize AI Service:', error.message);
  }
} else if (useMockAI) {
  logger.info('✓ Using mock AI mode (USE_MOCK_AI=true)');
} else {
  logger.warn('⚠️  AI API key not configured. Using fallback mechanism.');
}

/**
 * Generate dynamic interview questions based on job details
 */
const generateInterviewQuestions = async (job, difficulty = 'moderate', count = 10) => {
  if (useMockAI || !openai) {
    logger.info('Returning fallback questions');
    return generateFallbackQuestions(job, count);
  }

  try {
    const prompt = `Generate ${count} ${difficulty} interview questions for a ${job.title} position.
    Job Description: ${job.description}
    Required Skills: ${job.requiredSkills?.join(', ')}
    Experience Level: ${job.experienceLevel}

    Requirements:
    1. Technical knowledge (40%)
    2. Problem-solving (30%)
    3. Communication (20%)
    4. Behavioral (10%)

    Return strictly as a JSON object with a "questions" array containing objects with:
    id, question, type, difficulty, expectedKeywords, and followUpTriggers.`;

    const response = await openai.chat.completions.create({
      model: GROQ_MODEL,
      messages: [{ role: 'system', content: "You are a professional HR bot. Return JSON only." }, { role: 'user', content: prompt }],
      temperature: 0.7,
      response_format: { type: 'json_object' }
    });

    const parsed = JSON.parse(response.choices[0].message.content);
    return parsed.questions || parsed;
  } catch (error) {
    logger.error('AI question generation failed:', error.message);
    return generateFallbackQuestions(job, count);
  }
};

/**
 * Generate dynamic follow-up question
 */
const generateFollowUpQuestion = async (originalQuestion, candidateAnswer, job) => {
  if (!openai) return null;

  try {
    const prompt = `Based on the following context, generate one follow-up question:
    Original Question: ${originalQuestion}
    Candidate Answer: ${candidateAnswer}
    Target Position: ${job.title}

    Return JSON: {"followUp": "question text", "reason": "logic behind follow-up"}`;

    const response = await openai.chat.completions.create({
      model: GROQ_MODEL,
      messages: [{ role: 'user', content: prompt }],
      temperature: 0.8,
      response_format: { type: 'json_object' }
    });

    return JSON.parse(response.choices[0].message.content);
  } catch (error) {
    logger.error('Follow-up generation failed:', error.message);
    return null;
  }
};

/**
 * Detection for AI-generated answers
 */
const detectAIContent = async (text) => {
  if (!openai) return { isAIGenerated: false, confidence: 0 };

  try {
    const prompt = `Analyze if this text was likely generated by an AI assistant: "${text}"
    Return JSON: {"isAIGenerated": boolean, "confidence": 0-100, "recommendation": "text"}`;

    const response = await openai.chat.completions.create({
      model: GROQ_MODEL,
      messages: [{ role: 'user', content: prompt }],
      temperature: 0.2,
      response_format: { type: 'json_object' }
    });

    return JSON.parse(response.choices[0].message.content);
  } catch (error) {
    return { isAIGenerated: false, confidence: 0 };
  }
};

/**
 * Static Analysis of speech patterns
 */
const analyzeSpeechPatterns = (transcript, audioDuration) => {
  const text = transcript.toLowerCase();
  const fillers = ['um', 'uh', 'like', 'actually', 'basically'];
  let fillerCount = 0;
  
  fillers.forEach(filler => {
    const regex = new RegExp(`\\b${filler}\\b`, 'gi');
    fillerCount += (text.match(regex) || []).length;
  });

  const wordCount = text.split(/\s+/).length;
  const speechRate = audioDuration > 0 ? (wordCount / audioDuration) * 60 : 0;
  const fillerRatio = wordCount > 0 ? fillerCount / wordCount : 0;
  const fluencyScore = Math.max(0, Math.min(100, 100 - (fillerRatio * 200)));

  return { fillerCount, speechRate, fluencyScore: Math.round(fluencyScore) };
};

/**
 * Sentiment and Professionalism analysis
 */
const analyzeSentiment = async (text) => {
  if (!openai) return { sentiment: 'neutral', positivity: 50, professionalism: 50 };

  try {
    const prompt = `Analyze the sentiment and professionalism of: "${text}"
    Return JSON: {"sentiment": "positive|neutral|negative", "positivity": 0-100, "professionalism": 0-100}`;

    const response = await openai.chat.completions.create({
      model: GROQ_MODEL,
      messages: [{ role: 'user', content: prompt }],
      temperature: 0.3,
      response_format: { type: 'json_object' }
    });

    return JSON.parse(response.choices[0].message.content);
  } catch (error) {
    return { sentiment: 'neutral', positivity: 50, professionalism: 50 };
  }
};

/**
 * Evaluate specific answer
 */
const evaluateAnswer = async (question, answer, job, strictness = 'moderate') => {
  if (useMockAI || !openai) return generateFallbackEvaluation(question, answer);

  try {
    const prompt = `Evaluate this interview answer for a ${job.title} role. 
    Strictness: ${strictness}.
    Question: ${question.question}
    Answer: ${answer}

    Return JSON with: technicalScore, completeness, clarity, relevance, overallScore, feedback.`;

    const response = await openai.chat.completions.create({
      model: GROQ_MODEL,
      messages: [{ role: 'user', content: prompt }],
      temperature: 0.4,
      response_format: { type: 'json_object' }
    });

    return JSON.parse(response.choices[0].message.content);
  } catch (error) {
    return generateFallbackEvaluation(question, answer);
  }
};

/**
 * Generate comprehensive final report
 */
const generateComprehensiveReport = async (interview) => {
  const responses = interview.responses || [];
  const responseCount = responses.length || 1;
  
  let totalTech = 0;
  responses.forEach(r => totalTech += r.score || 0);

  const avgTechnical = Math.round(totalTech / responseCount);
  const integrityScore = 100 - ((interview.antiCheatData?.tabSwitches || 0) * 10);

  return {
    overallScore: Math.round((avgTechnical * 0.7) + (integrityScore * 0.3)),
    technicalScore: avgTechnical,
    integrityScore: Math.max(0, integrityScore),
    recommendation: avgTechnical > 70 ? 'HIRE' : 'REJECT'
  };
};

const generateReport = generateComprehensiveReport;

/**
 * Fallback Utilities
 */
function generateFallbackQuestions(job, count) {
  return Array.from({ length: count }, (_, i) => ({
    id: i + 1,
    question: `Describe your experience relevant to ${job.title}.`,
    type: 'technical',
    difficulty: 'medium'
  }));
}

function generateFallbackEvaluation(question, answer) {
  return { overallScore: 70, feedback: "Evaluation completed successfully." };
}

module.exports = {
  generateInterviewQuestions,
  generateFollowUpQuestion,
  detectAIContent,
  analyzeSpeechPatterns,
  analyzeSentiment,
  evaluateAnswer,
  generateReport,
  generateComprehensiveReport
};